---
- name: install builder
  hosts: builders
  become: yes

  tasks:

    - name: Ensure JDK is present
      apt:
        name: default-jdk
        state: present

    - name: Ensure MAVEN is present
      apt:
        name: maven
        state: present

    - name: Ensure GIT is present
      apt:
        name: git
        state: present

    - name: Get SRC APP from git
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /var/boxfuse_src

    - name: BUILD APP
      shell: mvn package
      args:
        chdir: /var/boxfuse_src

    - name: FETCH APP
      fetch:
        src: /var/boxfuse_src/target/hello-1.0.war
        dest: /tmp/hello-1.0.war


- name: Install WEB
  hosts: web
  become: yes

  tasks:

    - name: Ensure GIT is present
      apt:
        name: git
        state: present

    - name: Install TOMCAT9
      apt:
        name: tomcat9
        state: present

    - name: Ensure TOMCAT9 is started
      service:
        name: tomcat9
        state: started

    - name: COPY APP file
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps





